### ISSUE TITLE
Minor issues with the submitted 3.1.1package

### ISSUE THREAD

**Issue by boris-kolpackov** [build2-packaging/cxxopts#1]
Noticed the following minor issues, in case you want to fix them in the future:

1. Root `buildfile` mentions `tests/` but there aren't any. Not sure if these are planned in the future.
 
2. `include/buildfile` sets `bin.lib.version` even though this is a header-only library (and which seems unlikely to change).

**Comment by Rookfighter** [comment]
Hi @boris-kolpackov,
thanks again for the feedback. I fixed the issues in the latest revision.

1. Was a left-over. I had the tests integrated, but they use `std::auto_ptr` which is removed from the standard since c++17, so the tests would not build on any recent compiler with `cxx.std = latest`
